### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/obj-multiplex#7]
This project is missing a license file, would you mind adding one?

The `package.json` file suggests that the code is available under the ISC license,<sup>[\[1\]](https://github.com/kumavis/obj-multiplex/blob/8e55bbf614f0f2ec58c893afb699562bf5ceca4f/package.json#L10)</sup> which is [available on choosealicense.com](https://choosealicense.com/licenses/isc/)

**Comment by rekmarks** [comment]
This was done.
